// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQWGqEIAIlF3UQkUsyKyPrvaK-22FfWv0',
    appId: '1:407558919042:web:42ae45b72dd04f3881b59b',
    messagingSenderId: '407558919042',
    projectId: 'assignment4-ea1ba',
    authDomain: 'assignment4-ea1ba.firebaseapp.com',
    storageBucket: 'assignment4-ea1ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH1oj7SI2w8aeEa63_paxpH-4jX7WvWcc',
    appId: '1:407558919042:android:643cb70bc8c20a6b81b59b',
    messagingSenderId: '407558919042',
    projectId: 'assignment4-ea1ba',
    storageBucket: 'assignment4-ea1ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqRnZMaRv9GBnowodCpKmbqalmW41mAss',
    appId: '1:407558919042:ios:2568f86505de6cb081b59b',
    messagingSenderId: '407558919042',
    projectId: 'assignment4-ea1ba',
    storageBucket: 'assignment4-ea1ba.appspot.com',
    iosClientId:
        '407558919042-qrhep5gjc4upj7gsc3mcg1t4cth57lu7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqRnZMaRv9GBnowodCpKmbqalmW41mAss',
    appId: '1:407558919042:ios:2568f86505de6cb081b59b',
    messagingSenderId: '407558919042',
    projectId: 'assignment4-ea1ba',
    storageBucket: 'assignment4-ea1ba.appspot.com',
    iosClientId:
        '407558919042-qrhep5gjc4upj7gsc3mcg1t4cth57lu7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterdemo',
  );
}
